server {
    listen       8080;
    server_name  localhost;
    
    # defined in there
    # https://djangocas.dev/blog/nginx/nginx-access-log-with-real-x-forwarded-for-ip-instead-of-proxy-ip/
    # https://doc.traefik.io/traefik/reference/routing-configuration/http/middlewares/headers/#opt-Clients-IP
    real_ip_header    X-Forwarded-For;
    real_ip_recursive on;
    set_real_ip_from  127.0.0.0/8;
    set_real_ip_from  172.16.0.0/12;
    set_real_ip_from  10.0.0.0/8;
    set_real_ip_from  192.168.0.0/16;

    location / {
        root /usr/share/nginx/html;
        
        # https://dev.to/imsushant12/serving-static-content-with-nginx-26ih
        index index.html;
        try_files $uri $uri/ =404;  # Serve 404 if file not found

        # https://dev.to/imsushant12/serving-static-content-with-nginx-26ih
        location ~* \.(css|js|jpg|jpeg|png|gif|ico|svg)$ {
            expires 30d;  # Cache for 30 days
            access_log off;
        }
    }
}
