name: Validate IaC in PRs
'on':
  pull_request:
    paths:
      - '**/*.tf'
      - '.terraform.lock.hcl'

jobs:
  validate:
    name: Terraform Validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Format Check
        run: terraform fmt -check
      - name: Terraform Init
        run: terraform init
      - name: Validate Check
        run: terraform validate
