name: Validate Terraform in PRs
'on':
  pull_request
    paths:
    - '**.tf'
    - '.terraform.lock.hcl'
    - '.github/workflows/terraform-validate-pull-request.yml'

jobs:
  validate:
    if: '${{ github.event.pull_request.head.repo.full_name == github.repository }}'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
      - name: Format Check
        run: terraform fmt -check
      - name: Validate Check
        run: terraform validate
