name: 'Check Version'
on:
  pull_request:
    branches:
      - main
    paths:
      - 'src/**'
      - 'package*.json'
      - 'public/**'
      - '.github/workflows/version-pull-request.yml'

jobs:
  check_version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v2
      - name: Get branch package
        id: get_branch_version
        run: |
          branchJsonShell="$(cat package.json | tr -d '\n')"
          echo "::set-output name=branchJson::${branchJsonShell}"
      - name: Checkout main branch
        uses: actions/checkout@v2
        with:
          ref: main
      - name: Get main pacakge
        id: get_main_version
        run: |
          mainJsonShell="$(cat package.json | tr -d '\n')"
          echo "::set-output name=mainJson::${mainJsonShell}"
      - name: Compare branch and main package versions
        run: |
          branchVersion="${{fromJson(steps.get_branch_version.outputs.branchJson).version}}"
          branchMajor="$(echo "$branchVersion" | cut -d '-' -f1 | cut -d '.' -f1)"
          branchMinor="$(echo "$branchVersion" | cut -d '-' -f1 | cut -d '.' -f2)"
          branchPatch="$(echo "$branchVersion" | cut -d '-' -f1 | cut -d '.' -f3)"

          mainVersion="${{fromJson(steps.get_main_version.outputs.mainJson).version}}"
          mainMajor="$(echo "$mainVersion" | cut -d '-' -f1 | cut -d '.' -f1)"
          mainMinor="$(echo "$mainVersion" | cut -d '-' -f1 | cut -d '.' -f2)"
          mainPatch="$(echo "$mainVersion" | cut -d '-' -f1 | cut -d '.' -f3)"

          echo "Comparing branch version ($branchVersion) and main version: ($mainVersion):"

          if [ "$branchMajor" -gt "$mainMajor" ]; then
            echo "OK"
            exit 0
          elif [ "$branchMajor" -lt "$mainMajor" ]; then
            echo "--> Branch's package major version ($branchVersion) is out of date with main ($mainVersion) and needs to be updated."
            exit 1
          fi

          if [ "$branchMinor" -gt "$mainMinor" ]; then
            echo "OK"
            exit 0
          elif [ "$branchMinor" -lt "$mainMinor" ]; then
            echo "--> Branch's package minor version ($branchVersion) is out of date with main ($mainVersion) and needs to be updated."
            exit 1
          fi

          if [ "$branchPatch" -gt "$mainPatch" ]; then
            echo "OK"
            exit 0
          elif [ "$branchPatch" -lt "$mainPatch" ]; then
            echo "--> Branch's package patch version ($branchVersion) is out of date with main ($mainVersion) and needs to be updated."
            exit 1
          fi

          echo "--> Branch's package version ($branchVersion) needs to be bumped."
          exit 1
