name: 'Check Version'
on:
  pull_request:
    branches:
      - main
    paths:
      - 'src/**'
      - 'package*.json'
      - 'static/**'
      - Dockerfile
      - nginx.conf

jobs:
  check:
    name: Check
    uses: imyourmanzi/GitHubWorkflows/.github/workflows/npm-check-version.yml@main
