name: 'Check Version'
on:
  pull_request:
    branches:
      - main
    paths:
      - 'src/**'
      - 'package*.json'
      - 'public/**'

jobs:
  check:
    name: Check
    uses: imyourmanzi/GitHubWorkflows/.github/workflows/package-json-version-check.yml@main
