name: 'Check Version'
on:
  pull_request:
    branches:
      - main
    paths:
      - 'src/**'
      - 'package*.json'
      - 'public/**'
      - '.github/workflows/version-pull-request.yml'

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: imyourmanzi/GitHubWorkflows/.github/workflows/package-json-version-check.yml@main
